/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tfmsihuac.tfmsihuac;

import Controladores.metodos;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Luis Fernando
 */
public class Principal extends javax.swing.JFrame {
    metodos metodo = new metodos();
    Dimension screenSize;
    int anchoVentana;
    int altoVentana;
        
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        anchoVentana = screenSize.width; 
        altoVentana = screenSize.height-metodo.tamaños(anchoVentana, 260);
        System.out.println(anchoVentana +" - "+ altoVentana);
        this.setBounds(0, 0, anchoVentana, altoVentana);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Informático de Hosteria La Huaca");
        setResizable(false);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
